### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by msabramo** [hubot-scripts/hubot-auth#21]
It looks like the tests have been failing for a while, because of [some issue with mock-adaptor and the latest version of hubot](https://github.com/hubot-scripts/hubot-auth/pull/20#issuecomment-150954112)?

@michaelansel: Do you have recommendations for how @patcon can fix the tests?

It looks like https://github.com/michaelansel/hubot-approval/blob/master/test/approval-test.coffee is using a combination of `chai`, `sinon`, and `sinon-chai`. I don't know what those things are because I'm new to NodeJS, but I saw hubot-approval using them, so maybe they're the current state of the art?

**Comment by michaelansel** [comment]
Figuring out testing patterns is an open issue on the core: https://github.com/github/hubot/issues/985

Hopefully getting to it someday?

**Comment by patcon** [comment]
Thanks folks :) Sorry I can't sort it out myself, but happy to merge solutions

**Comment by patcon** [comment]
Re: @michaelansel https://github.com/hubot-scripts/hubot-auth/pull/20#issuecomment-152669692

> Up to @patcon to decide how to handle failing tests for his project.

I'm actually hands-off on this project atm, so hoping someone who values testing can submit a PR for getting them up and running again :)

Also, totally willing to add that person who fixes up testing as a new collaborator
