### ISSUE TITLE
Secondary userid delimiter support

### ISSUE THREAD

**Issue by vwbusguy** [hubot-scripts/hubot-auth#22]
Ref. https://issues.jenkins-ci.org/browse/JENKINS-31350

We're deploying hubot with Docker and the docker-build-step plugin in Jenkins comma-delimits the container environment variables.  This means we can only specify one user id when deploying this from Jenkins.

While I've filed a bug against the Jenkins plugin, it's possible this issue may come up for others, and adding a second delimiter in hubot-auth is a much easier task, given the user id format and code simplicity.

**Comment by vwbusguy** [comment]
The simplest example to allow , and ; would be:

 admins = config.admin_list.split '/[:,]+/'

In line 34 of src/auth.coffee .  If this is acceptable, I can make this into a pull request?

**Comment by patcon** [comment]
Sure thing! :) but maybe add a comment above, referencing that ticket you linked, so it explains itself for later?

**Comment by nick-woodward** [comment]
I'm going to close this since this ticket is over a year old and a PR was never submitted. 

Feel free to open a new ticket + PR if the feature is still wanted.
