### ISSUE TITLE
Command to list custom roles?

### ISSUE THREAD

**Issue by zGrav** [hubot-scripts/hubot-auth#26]
Hey all,

Is it possible to save a new custom role upon adding it to user (making a new section in hubot's brain for custom roles) and then listing them when asked?

I'll try to make a PR when I get some code up.

Regards.

**Comment by zGrav** [comment]
Delete custom roles added to #27

**Comment by nick-woodward** [comment]
I think the meat of what you want is a more structured role system. Where roles are their own entity rather then being linked directly to users.

Can you give a use-case where this would be useful to you?

**Comment by zGrav** [comment]
Possibly @ceci-woodward , although hubot-auth does do what it is intended to do and works just fine for us.

Our edge case is pretty much we have our Admins in the environment variable of hubot-auth and we've built some scripts (in this case an rss reader) that should only be accessed/used by admins and people in the rss role, hence custom roles.

Regards.

**Comment by patcon** [comment]
fwiw, what you're calling "custom roles" is, as I understand it, not an edge case but the main thrust of what hubot-auth is intended to be used for. The "custom" qualifier was confusing me a bit at first tbh :)

**Comment by zGrav** [comment]
@patcon Sorry, I tend to confuse people with my attempts at doing things properly haha

**Comment by zGrav** [comment]
Merged, thanks once more!
