### ISSUE TITLE
As an Ops, I want to be able to configure hubot-auth roles in order to be idempotent

### ISSUE THREAD

**Issue by vspiewak** [hubot-scripts/hubot-auth#31]
I don't see any mechanism to pre-configure some roles automatically (with an environment variable for instance).
I can install hubot-auth, setup some roles persisted in Redis Brain using hubot commands.

But, if my redis or hubot crash, I have to setup roles again.

What do you think ?

Best Regards

**Comment by patcon** [comment]
I'm not opposed :) eager to hear what others have to say though, as I'm not using this script right now

**Comment by nick-woodward** [comment]
I can look into this when I get home.

Does something like this work for you @vspiewak?

HUBOT_AUTH_ROLES="other_role=U12345678,U12345679 another_role=U12345678"

Or can you think of a better syntax?

**Comment by vspiewak** [comment]
This cool be great 👍 
Using immutable infrastructure intensively, I noticed this problem on any hubot-script requiring some initial chat as setup.
It include for instance [hubot-standup-alarm](https://github.com/hubot-scripts/hubot-standup-alarm)

Maybe we should look at [events](https://leanpub.com/automation-and-monitoring-with-hubot/read#leanpub-auto-cross-script-communication-with-events) ?
