### ISSUE TITLE
Unable to unassign role once assigned

### ISSUE THREAD

**Issue by sravan-bala** [hubot-scripts/hubot-auth#33]
Thanks for hubot-auth. It really helped to restrict commands, which is great. I integrated hubot with hipchat. Assigned roles and its working good. While un-assigning role, instead of 

`hubot jester doesn't have deploy role` I typed 
`hubot jester doesn`t have deploy role `

Hubot replied as 
`jester doesn't does not exist`. 

But when I typed 
`hubot jester doesn't have deploy role`
Hubot replied as 

```
jester doesn't does not exist
OK, jester doesn't have the 'deploy' role.
```

On whole it works, but is there a way to not display unnecessary messages. Am I missing something? Thanks!

**Comment by nick-woodward** [comment]
@sravan-bala Can you verify if this is still an issue with the latest version of `hubot-auth`?

**Comment by sravan-bala** [comment]
As, the purpose why we want this has been changed we moved to a different solution. So I didnt get a chance to work on this later. Thank you!

**Comment by nick-woodward** [comment]
@sravan-bala Thanks for your quick response!

I'm going to close this issue, if anyone comes across this again they can open a new one.
