### ISSUE TITLE
List Assigned Roles gets no response (Latest code not downloading/installing through NPM)

### ISSUE THREAD

**Issue by chriskol** [hubot-scripts/hubot-auth#34]
The list assigned roles command gets no response when I issue it with hubot.  No errors or any messages from hubot.  Just nothing as if the command weren't recognized. All other commands are fine (if I ask it what roles I have, or what roles a specific user has, or who has a specific role, it works fine).  I think this may have something to do with my [hubot standup script not recognizing any members of roles] (https://github.com/miyagawa/hubot-standup/issues/10#issuecomment-226355417).

**Comment by chriskol** [comment]
Hey I'm a bit new to this but it looks like the version of hubot-auth I'm installing via npm is not the same as is on github.  For instance the 'List Assigned Roles' function is not even in the auth.coffee version I'm downloading via npm.  Tried deleting the folder in node_modules and reinstalling and it seems to be installing an old version.

**Comment by chriskol** [comment]
It's looking like a new 'release' needs to be made to reflect the new changes?

**Comment by chriskol** [comment]
Jesus, sorry for the spam but would something like this be better to implement in the package.json file?

http://stackoverflow.com/questions/23338393/npm-install-not-installing-latest-version-on-github

**Comment by chriskol** [comment]
I'm a big ol idiot and learned I can just change the package.json to use     

"hubot-auth": "github:hubot-scripts/hubot-auth",

instead of the latest version

**Comment by patcon** [comment]
Heh. No worries -- there technically should be a new release. But yeah, the alt syntax works when that hasn't been done :)

Just release v1.3.0 :fireworks:
